### ISSUE TITLE
Can't get local attribute 'build_quantity_class.<locals>.Quantity' when serializing with Dill

### ISSUE THREAD

**Issue by jellespijker** [hgrecco/serialize#2]
Hello,

I'm trying to serialize a custom class containing Pint Quantities and (lambda) functions. Because of the (lambda) functions I have to use Dill. When I use the code sample provided at [Pint serialization](http://pint.readthedocs.io/en/0.7.2/serialization.html) I get an pickle `AttributeError: Can't get local attribute 'build_quantity_class.<locals>.Quantity' on <function build_quantity_class at 0x03864198>` 
```py
from serialize import dump as serialize_dump, load as serialize_load, register_class
from pint import UnitRegistry
u = UnitRegistry(autoconvert_offset_to_baseunit=True)

register_class(u.Quantity, u.Quantity.to_tuple, u.Quantity.from_tuple)

class Test(object):
    def __init__(self):
        self.x = 10 * u['m/s']
        self.y = lambda x: x**2

test = Test()
serialize_dump(test, 'test.tst', fmt='dill')
test_return = serialize_load('test.tst', fmt='dill')
print(test.x, test.y(test.x))
print(test_return.x, test_return.y(test.x))
```
Gives the following error:
```commandline
D:\Projects\mti\virtualEnv\Scripts\python.exe D:/Projects/mti/MTIpython/Sandbox/serialize_pint_w_dill.py
Traceback (most recent call last):
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 918, in save_global
    obj2, parent = _getattribute(module, name)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 266, in _getattribute
    .format(name, obj))
AttributeError: Can't get local attribute 'build_quantity_class.<locals>.Quantity' on <function build_quantity_class at 0x03864198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Projects/mti/MTIpython/Sandbox/serialize_pint_w_dill.py", line 21, in <module>
    serialize_dump(test, 'test.tst', fmt='dill')
  File "D:\Projects\mti\virtualEnv\lib\site-packages\serialize\all.py", line 308, in dump
    dump(obj, fp, fmt)
  File "D:\Projects\mti\virtualEnv\lib\site-packages\serialize\all.py", line 310, in dump
    _get_format(fmt).dump(obj, filename_or_file)
  File "D:\Projects\mti\virtualEnv\lib\site-packages\serialize\dill.py", line 29, in dump
    MyPickler(fp).dump(obj)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 409, in dump
    self.save(obj)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 634, in save_reduce
    save(state)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Projects\mti\virtualEnv\lib\site-packages\dill\dill.py", line 871, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 609, in save_reduce
    save(func)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Projects\mti\virtualEnv\lib\site-packages\dill\dill.py", line 1047, in save_instancemethod0
    pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 610, in save_reduce
    save(args)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 736, in save_tuple
    save(element)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Projects\mti\virtualEnv\lib\site-packages\dill\dill.py", line 1299, in save_type
    StockPickler.save_global(pickler, obj)
  File "C:\Users\install\AppData\Local\Programs\Python\Python36-32\lib\pickle.py", line 922, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <class 'pint.quantity.build_quantity_class.<locals>.Quantity'>: it's not found as pint.quantity.build_quantity_class.<locals>.Quantity

Process finished with exit code 1

```

But when I define my own to and from functions pointing returning `u.Quantity.to_tuple(c)` or  `u.Quantity.from_tuple(c)` the code works again.

```py
from serialize import dump as serialize_dump, load as serialize_load, register_class
from pint import UnitRegistry
u = UnitRegistry(autoconvert_offset_to_baseunit=True)

def to_tuple(c):
    return u.Quantity.to_tuple(c)

def from_tuple(c):
    return u.Quantity.from_tuple(c)

register_class(u.Quantity, to_tuple, from_tuple)

class Test(object):
    def __init__(self):
        self.x = 10 * u['m/s']
        self.y = lambda x: x**2

test = Test()
serialize_dump(test, 'test.tst', fmt='dill')
test_return = serialize_load('test.tst', fmt='dill')
print(test.x, test.y(test.x))
print(test_return.x, test_return.y(test.x))
```

**Comment by hgrecco** [comment]
I think the problem is that dill requires to access to the actual serializing and deserializing function. But in the first case, the class (`Quantity`) containing these functions (`to_tuple`, `from_tuple`) is dynamically built (in `build_quantity_class`).
